namespace BSE.Modules.ReferenceData.Models;

/// <summary>
/// Maps to luAHRO via GetluAHRO.
/// TtblId is the sequential identity generated by the SP's temp table; Id is the source table's own integer PK.
/// </summary>
public record LuAHRO
{
    public int TtblId { get; init; }
    public int Id { get; init; }
    public string Name { get; init; } = string.Empty;
}
