CREATE USER [TSTBSEWEBAW1401] FROM EXTERNAL PROVIDER;
ALTER ROLE db_datareader ADD MEMBER [TSTBSEWEBAW1401];
ALTER ROLE db_datawriter ADD MEMBER [TSTBSEWEBAW1401];
 
-----------------------------
GRANT EXECUTE ON [TSTBSEWEBAW1401];