'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CaseEntryClinical

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblRBSEHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litViewDocs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litViewDocs2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''hlbFarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbFarm As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbCaseDEFRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbCaseDEFRA As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbBAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbBAB As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbCaseVLA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbCaseVLA As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbFeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbFeeds As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbRelations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbRelations As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblApprehension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprehension As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAbnormalBehaviour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbnormalBehaviour As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHypersensitiveTouch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHypersensitiveTouch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHypersensitiveSound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHypersensitiveSound As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblManiacal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblManiacal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPanicStricken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPanicStricken As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTemperamentChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTemperamentChange As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAbnormalHeadCarriage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbnormalHeadCarriage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEarTwitching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEarTwitching As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEarsOddAngle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEarsOddAngle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHeadShyness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeadShyness As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLickingFlank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLickingFlank As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLickingNose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLickingNose As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKicking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKicking As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblReluctantToEnterDoorways control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReluctantToEnterDoorways As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHeadPressing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeadPressing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHeadRubbing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeadRubbing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTeethGrinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeethGrinding As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBlindness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlindness As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFalling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFalling As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRecumbent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecumbent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCircling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCircling As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHindAtaxia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHindAtaxia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblParesis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParesis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblForeAtaxia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblForeAtaxia As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTremor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTremor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKnucklingFetlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKnucklingFetlock As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWeightLoss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWeightLoss As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblConditionLoss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConditionLoss As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMilkYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMilkYield As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkApprehension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkApprehension As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHypersensitiveTouch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHypersensitiveTouch As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHypersensitiveSound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHypersensitiveSound As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkManiacal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkManiacal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPanicStricken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPanicStricken As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTemperamentChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTemperamentChange As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAbnormalHeadCarriage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAbnormalHeadCarriage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEarTwitching control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEarTwitching As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEarsOddAngle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEarsOddAngle As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAbnormalBehaviour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAbnormalBehaviour As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHeadShyness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHeadShyness As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkLickingFlank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLickingFlank As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkLickingNose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLickingNose As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkKicking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkKicking As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkReluctantToEnterDoorways control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReluctantToEnterDoorways As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHeadPressing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHeadPressing As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHeadRubbing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHeadRubbing As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTeethGrinding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTeethGrinding As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkBlindness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBlindness As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCircling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCircling As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkHindAtaxia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHindAtaxia As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkFalling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkFalling As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkParesis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkParesis As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkForeAtaxia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkForeAtaxia As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRecumbent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRecumbent As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTremor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTremor As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkKnucklingFetlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkKnucklingFetlock As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWeightLoss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWeightLoss As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkConditionLoss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkConditionLoss As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMilkYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMilkYield As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblClinicalVisitDates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClinicalVisitDates As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdClinicalVisit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdClinicalVisit As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litViewDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litViewDocs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''VLAFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAFooter1 As Global.BSESystem.VLAFooter
End Class
