'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CaseWorkEntry

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''VLAHeader1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAHeader1 As Global.BSESystem.VLAHeader

    '''<summary>
    '''btnSaveTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveTop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancelTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelTop As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Scriptmanager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scriptmanager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblRBSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStatusValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatusValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRBSEValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEValue As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblRBSEDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRBSEDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormADate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormADate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormADateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormADateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormBDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormBDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFormBDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormBDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSlaughterDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlaughterDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSlaughterDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlaughterDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrigin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOriginValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOriginValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSurvey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSurvey As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSurveyValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSurveyValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBarcodeValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcodeValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAHFReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAHFReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAHFReferenceValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAHFReferenceValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRegionalLab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegionalLab As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRegionalLabValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionalLabValue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRegionalLabReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegionalLabReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlRegionalLabReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlRegionalLabReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblInitialReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInitialReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlInitialReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlInitialReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblFinalReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlFinalReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlFinalReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblFinalResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFinalResultValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalResultValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFinalResultDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalResultDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFinalResultDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalResultDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDBSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDBSE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDBSEValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDBSEValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlternateDiagnosis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlternateDiagnosis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlternateDiagnosisValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlternateDiagnosisValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFinalSentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalSentDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlFinalSentDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlFinalSentDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBirthDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBirthDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBirthDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaperworkReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaperworkReceived As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchaserBSE1ReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchaserBSE1ReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlPurchaserBSE1ReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPurchaserBSE1ReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblBreederBSE1ReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBreederBSE1ReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlBreederBSE1ReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlBreederBSE1ReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblVendor1BSE1ReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVendor1BSE1ReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlVendor1BSE1ReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlVendor1BSE1ReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblHomeBredBSE1ReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHomeBredBSE1ReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlHomeBredBSE1ReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlHomeBredBSE1ReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblSummarySheetReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummarySheetReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlSummarySheetReceivedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlSummarySheetReceivedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblPaperworkCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaperworkCompleteDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlPaperworkCompleteDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPaperworkCompleteDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblDataCompleteDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataCompleteDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlDataCompleteDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDataCompleteDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblTseTestingsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTseTestingsite As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTseTestingsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTseTestingsite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''aceTseTestingSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aceTseTestingSite As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''lblSamplingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSamplingDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAHRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAHRO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAHRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAHRO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMinutesDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinutesDue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMinuteSentOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinuteSentOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveMemoDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveMemoDueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveMemoDueDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveMemoDueDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexADueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexADueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexADueDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexADueDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexBDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexBDueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexBDueDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexBDueDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexCDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexCDueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexCDueDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexCDueDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexDDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexDDueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexDDueDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexDDueDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveMemoDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveMemoDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexADateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexADateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexBDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexBDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexCDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexCDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAnnexDDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnnexDDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLabChaseDueDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabChaseDueDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblChasedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChasedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLabChaseDueDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLabChaseDueDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlLabChasedDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlLabChasedDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''lblBarbMemoDue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarbMemoDue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSentOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSentOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBarbMemoDueValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarbMemoDueValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlBarbMemoDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlBarbMemoDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''chkOpenCloseCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOpenCloseCase As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCaseworkComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseworkComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCaseworkComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaseworkComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnActiveMemoSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnActiveMemoSend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnexASend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnexASend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnexBSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnexBSend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnexCSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnexCSend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnexDSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnexDSend As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBirthDateAfter2000 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBirthDateAfter2000 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDefraInformedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefraInformedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ctlPost2000SentDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlPost2000SentDateValue As Global.BSESystem.CalendarDate

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VLAFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAFooter1 As Global.BSESystem.VLAFooter
End Class
