'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CaseEntryVLA

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblRBSEHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litViewDocs2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litViewDocs2 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''hlbFarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbFarm As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbCaseDEFRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbCaseDEFRA As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbBAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbBAB As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbClinical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbClinical As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbFeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbFeeds As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlbRelations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlbRelations As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateOfBirth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBreed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBreed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrigin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDatePurchased control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDatePurchased As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAgePurchased control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgePurchased As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPurchasedCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPurchasedCounty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHerdEntryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHerdEntryDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonthsPregnant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonthsPregnant As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMonthsPostCalving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonthsPostCalving As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetAge As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSlaughterDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSlaughterDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateOfBirthEstimated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateOfBirthEstimated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetDateEstimated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetDateEstimated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAgePurchasedYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgePurchasedYears As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAgePurchasedMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAgePurchasedMonths As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetAgeYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetAgeYears As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetAgeMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetAgeMonths As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetAgeIncorrect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetAgeIncorrect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPregnantError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPregnantError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnsetDateWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnsetDateWarning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPreviousOwners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreviousOwners As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateOfBirthSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateOfBirthSource As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''revMonthsPostCalving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revMonthsPostCalving As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revMonthsPregnant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revMonthsPregnant As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revAgePurchasedYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAgePurchasedYears As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revAgePurchasedMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAgePurchasedMonths As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revOnsetAgeYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revOnsetAgeYears As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revOnsetAgeMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revOnsetAgeMonths As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ddlBirthDateSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBirthDateSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkDateOfBirthEstimated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDateOfBirthEstimated As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSex As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBreed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBreed As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrigin As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCalculateAgePurchased control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalculateAgePurchased As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddlPurchasedCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPurchasedCounty As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAgePurchasedYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgePurchasedYears As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAgePurchasedMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgePurchasedMonths As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHerdDateWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHerdDateWarning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkOnsetDateEstimated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOnsetDateEstimated As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtMonthsPregnant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonthsPregnant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMonthsPostCalving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonthsPostCalving As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCalculateOnsetAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalculateOnsetAge As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtOnsetAgeYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnsetAgeYears As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOnsetAgeMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnsetAgeMonths As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInformDEFRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInformDEFRA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdOtherOwners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdOtherOwners As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''btnCaseAuditLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCaseAuditLog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''litViewDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litViewDocs As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''VLAFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAFooter1 As Global.BSESystem.VLAFooter
End Class
