'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''CPHH class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class CPHH

    '''<summary>
    '''txtCPHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCPHH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvalid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvalid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''revCPHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revCPHH As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvCPHH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCPHH As Global.System.Web.UI.WebControls.RequiredFieldValidator
End Class
