'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''MapReference class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class MapReference

    '''<summary>
    '''txtMapReference1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapReference1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMapReference2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapReference2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMapReference3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapReference3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revMapReference1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revMapReference1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revMapReference2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revMapReference2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revMapReference3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revMapReference3 As Global.System.Web.UI.WebControls.RegularExpressionValidator
End Class
