'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''MoveCaseNewFarm class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class MoveCaseNewFarm

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblRBSEHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCPHHHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPHHHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOwnerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPostcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCorrespondenceAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorrespondenceAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblParish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParish As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCorrespondencePostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorrespondencePostcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCounty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMapReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMapReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAHO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAHO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHerdmark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHerdmark1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHerdmark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHerdmark2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumericHerdmark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumericHerdmark1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumericHerdmark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumericHerdmark2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHerdmark3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHerdmark3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInvalidMapReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvalidMapReference As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''revHerdmark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revHerdmark1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revHerdmark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revHerdmark2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revNumericHerdmark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumericHerdmark1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''revNumericHerdmark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumericHerdmark2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblADNSRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblADNSRegion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOwnerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOwnerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtParish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParish As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistrict As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCounty As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAHO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAHO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnEstimate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEstimate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUseAboveAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUseAboveAddress As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtCorrespondenceAddress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrespondenceAddress1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCorrespondenceAddress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrespondenceAddress2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCorrespondenceAddress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrespondenceAddress3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCorrespondencePostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorrespondencePostcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAuthorityCounty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAuthorityCounty As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlLocalAuthority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocalAuthority As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlADNSRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlADNSRegion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtHerdmark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHerdmark1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHerdmark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHerdmark2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHerdmark3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHerdmark3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNumericHerdmark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumericHerdmark1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNumericHerdmark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumericHerdmark2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VLAFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAFooter1 As Global.BSESystem.VLAFooter
End Class
