'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''RelationsPopup class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class RelationsPopup

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblRBSEHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRBSEHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamEartag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamEartag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamBirthDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamRBSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamRBSE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamFate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamFate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFinalResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFinalResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamFinalResultValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamFinalResultValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireEartag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireEartag As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireRBSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireRBSE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireFate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireFate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireBirthDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireBirthDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamFateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamFateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireFateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireFateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamEartagValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamEartagValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamRBSEValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamRBSEValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamNameValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamNameValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamBirthDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamBirthDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireEartagValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireEartagValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireRBSEValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireRBSEValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireNameValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireNameValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireBirthDateValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireBirthDateValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOtherRelations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOtherRelations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireHerdbook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireHerdbook As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireHerdbookValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireHerdbookValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireOffspring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireOffspring As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSireOffspringCountValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSireOffspringCountValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamOffspringCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamOffspringCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamOffspringCountValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamOffspringCountValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamHerdbook control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamHerdbook As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDamHerdbookValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDamHerdbookValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdRelations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRelations As Global.System.Web.UI.WebControls.DataGrid
End Class
