CREATE TABLE [dbo].[CaseWork] (
    [RBSE]                      CHAR (9)      NOT NULL,
    [RBSEDate]                  DATETIME      NOT NULL,
    [Barcode]                   VARCHAR (20)  NULL,
    [AHFReference]              VARCHAR (40)  NULL,
    [PurchaserBSE1ReceivedDate] DATETIME      NULL,
    [BreederBSE1ReceivedDate]   DATETIME      NULL,
    [Vendor1BSE1ReceivedDate]   DATETIME      NULL,
    [HomebredBSE1ReceivedDate]  DATETIME      NULL,
    [SummarySheetReceivedDate]  DATETIME      NULL,
    [PaperworkCompleteDate]     DATETIME      NULL,
    [ActiveMemoDate]            DATETIME      NULL,
    [AnnexADate]                DATETIME      NULL,
    [AnnexBDate]                DATETIME      NULL,
    [AnnexCDate]                DATETIME      NULL,
    [AnnexDDate]                DATETIME      NULL,
    [RegionalLab]               CHAR (4)      NULL,
    [ReceivedByRegionalLabDate] DATETIME      NULL,
    [InitialReceivedDate]       DATETIME      NULL,
    [FinalReceivedDate]         DATETIME      NULL,
    [FinalSentDate]             DATETIME      NULL,
    [LabChasedDate]             DATETIME      NULL,
    [BarbMinuteSentDate]        DATETIME      NULL,
    [Post2000SentDate]          DATETIME      NULL,
    [CaseWorkNotes]             VARCHAR (500) NULL,
    [DataCompleteDate]          DATETIME      NULL,
    [IsCaseClosed]              BIT           CONSTRAINT [DF_CaseWork_IsCaseClosed] DEFAULT (0) NOT NULL,
    [RowStamp]                  ROWVERSION    NOT NULL,
    [TSETestingSite]            VARCHAR (50)  NULL,
    [SamplingDate]              DATETIME      NULL,
    [AHRO]                      INT           NULL,
    CONSTRAINT [PK_CaseWork] PRIMARY KEY CLUSTERED ([RBSE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CK_CaseWork_ActiveMemoDate] CHECK ([ActiveMemoDate] is null or [ActiveMemoDate] >= [RBSEDate]),
    CONSTRAINT [CK_CaseWork_AnnexADate] CHECK ([AnnexADate] is null or [AnnexADate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_AnnexBDate] CHECK ([AnnexBDate] is null or [AnnexBDate] > [AnnexADate]),
    CONSTRAINT [CK_CaseWork_AnnexCDate] CHECK ([AnnexCDate] is null or [AnnexCDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_AnnexDDate] CHECK ([AnnexDDate] is null or [AnnexDDate] > [AnnexCDate]),
    CONSTRAINT [CK_CaseWork_BarbMinuteSentDate] CHECK ([BarbMinuteSentDate] is null or [BarbMinuteSentDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_BreederBSE1ReceivedDate] CHECK ([BreederBSE1ReceivedDate] is null or [BreederBSE1ReceivedDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_DataCompleteDate] CHECK ([DataCompleteDate] is null or [DataCompleteDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_FinalReceivedDate] CHECK ([FinalReceivedDate] is null or [FinalReceivedDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_FinalSentDate] CHECK ([FinalSentDate] is null or [FinalSentDate] >= [FinalReceivedDate]),
    CONSTRAINT [CK_CaseWork_HomebredBSE1ReceivedDate] CHECK ([HomebredBSE1ReceivedDate] is null or [HomebredBSE1ReceivedDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_LabChasedDate] CHECK ([LabChasedDate] is null or [LabChasedDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_PaperworkCompleteDate] CHECK ([PaperworkCompleteDate] is null or [PaperworkCompleteDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_Post2000SentDate] CHECK ([Post2000SentDate] is null or [Post2000SentDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_PurchaserBSE1ReceivedDate] CHECK ([PurchaserBSE1ReceivedDate] is null or [PurchaserBSE1ReceivedDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_SummarySheetReceivedDate] CHECK ([SummarySheetReceivedDate] is null or [SummarySheetReceivedDate] > [RBSEDate]),
    CONSTRAINT [CK_CaseWork_Vendor1BSE1ReceivedDate] CHECK ([Vendor1BSE1ReceivedDate] is null or [Vendor1BSE1ReceivedDate] > [RBSEDate]),
    CONSTRAINT [FK_CaseWork_AHRO] FOREIGN KEY ([AHRO]) REFERENCES [dbo].[luAHRO] ([Id]),
    CONSTRAINT [FK_CaseWork_Case] FOREIGN KEY ([RBSE]) REFERENCES [dbo].[Case] ([RBSE]),
    CONSTRAINT [FK_CaseWork_luRegionalLab] FOREIGN KEY ([RegionalLab]) REFERENCES [dbo].[luRegionalLab] ([Code])
);

