CREATE TABLE [dbo].[Case] (
    [RBSE]                    CHAR (9)      NOT NULL,
    [CPHH]                    CHAR (11)     NOT NULL,
    [EartagHerdmark]          VARCHAR (8)   NULL,
    [Eartag]                  VARCHAR (25)  NULL,
    [IsNonGBCase]             BIT           NOT NULL,
    [PreviousEartag]          VARCHAR (25)  NULL,
    [BSE1ReceivedDate]        DATETIME      NULL,
    [FormADate]               DATETIME      NULL,
    [FormAResubmittedDate]    DATETIME      NULL,
    [FormBDate]               DATETIME      NULL,
    [Fate]                    VARCHAR (4)   NULL,
    [FormCDate]               DATETIME      NULL,
    [IsPurchaserBSE1Received] BIT           CONSTRAINT [DF_Case_IsPurchaserBSE1Received] DEFAULT (0) NOT NULL,
    [IsBreederBSE1Received]   BIT           CONSTRAINT [DF_Case_IsBreederBSE1Received] DEFAULT (0) NOT NULL,
    [IsVendor1BSE1Received]   BIT           CONSTRAINT [DF_Case_IsVendor1BSE1Received] DEFAULT (0) NOT NULL,
    [IsHomebredBSE1Received]  BIT           CONSTRAINT [DF_Case_IsVendor2BSE1Received] DEFAULT (0) NOT NULL,
    [IsSummarySheetReceived]  BIT           CONSTRAINT [DF_Case_IsSummarySheetReceived] DEFAULT (0) NOT NULL,
    [IsPaperworkComplete]     BIT           CONSTRAINT [DF_Case_IsPaperworkComplete] DEFAULT (0) NOT NULL,
    [FinalResultDate]         DATETIME      NULL,
    [FinalResult]             VARCHAR (5)   NULL,
    [Methodology]             VARCHAR (10)  NULL,
    [DBSE]                    CHAR (7)      NULL,
    [ReportedLocation]        VARCHAR (5)   CONSTRAINT [DF_Case_ReportedLocation] DEFAULT ('OF') NULL,
    [Survey]                  VARCHAR (4)   NULL,
    [Notes]                   VARCHAR (500) NULL,
    [BirthDate]               DATETIME      NULL,
    [IsBAB]                   BIT           NULL,
    [IsBirthDateEst]          BIT           NULL,
    [DamStatus]               VARCHAR (9)   NULL,
    [BirthDateSource]         VARCHAR (5)   NULL,
    [ValuationAge]            CHAR (1)      NULL,
    [Sex]                     CHAR (1)      NULL,
    [Breed]                   VARCHAR (20)  NULL,
    [Origin]                  CHAR (1)      NULL,
    [PurchaseDate]            DATETIME      NULL,
    [PurchaseAgeInMonths]     SMALLINT      NULL,
    [PurchasedCounty]         VARCHAR (15)  NULL,
    [HerdEntryDate]           DATETIME      NULL,
    [OnsetDate]               DATETIME      NULL,
    [IsOnsetDateEst]          BIT           NULL,
    [MonthsPregnant]          TINYINT       NULL,
    [MonthsPostCalving]       TINYINT       NULL,
    [OnsetAgeInMonths]        SMALLINT      NULL,
    [SlaughterDate]           DATETIME      NULL,
    [EmailSentToADNSDate]     DATETIME      NULL,
    [ADNSReferenceYear]       SMALLINT      NULL,
    [ADNSReferenceNumber]     INT           NULL,
    [RetrospectiveTestType]   VARCHAR (10)  NULL,
    [RetrospectiveResult]     VARCHAR (5)   NULL,
    [RetrospectiveResultDate] DATETIME      NULL,
    [RetrospectiveComment]    VARCHAR (500) NULL,
    [RowStamp]                ROWVERSION    NOT NULL,
    [AlternateDiagnosis]      VARCHAR (255) NULL,
    [LabComment]              VARCHAR (255) NULL,
    [EartagCountry]           VARCHAR (4)   NULL,
    [CaseType]                VARCHAR (2)   NULL,
    [IsoFormatEartag]         BIT           CONSTRAINT [DF_Case_IsoFormatEartag] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Case] PRIMARY KEY CLUSTERED ([RBSE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CK_Case_AlternateDiagnosis] CHECK ([FinalResult] = 'Neg' or [FinalResult] <> 'Neg' and [AlternateDiagnosis] is null),
    CONSTRAINT [CK_Case_BirthDate] CHECK ([BirthDate] <= isnull([FormADate],getdate()) and [BirthDate] >= '1 January 1970'),
    CONSTRAINT [CK_Case_BirthDateSource] CHECK ([BirthDate] is null and [BirthDateSource] is null or [BirthDate] is not null),
    CONSTRAINT [CK_Case_BSE1ReceivedDate] CHECK ([BSE1ReceivedDate] <= getdate()),
    CONSTRAINT [CK_Case_CPHH] CHECK ([CPHH] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [CK_Case_DBSE] CHECK (isnull([FinalResult],'') = 'Pos' and [DBSE] is not null or [DBSE] is null),
    CONSTRAINT [CK_Case_FinalResultDate] CHECK ([FinalResultDate] <= getdate()),
    CONSTRAINT [CK_Case_FormADate] CHECK ([IsNonGBCase] = 1 and [FormADate] is null or [IsNonGBCase] = 0 and [FormADate] <= getdate()),
    CONSTRAINT [CK_Case_FormAResubmittedDate] CHECK ([FormADate] is not null and [FormAResubmittedDate] is not null and [FormAResubmittedDate] <= getdate() or [FormAResubmittedDate] is null),
    CONSTRAINT [CK_Case_FormBDate] CHECK ([FormADate] is not null and [FormBDate] is not null and [FormBDate] <= getdate() and [FormBDate] >= [FormADate] or [FormBDate] is null),
    CONSTRAINT [CK_Case_IsBirthDateEst] CHECK ([BirthDate] is null and [IsBirthDateEst] is null or [BirthDate] is not null and [IsBirthDateEst] is not null),
    CONSTRAINT [CK_Case_IsOnsetDateEst] CHECK ([OnsetDate] is null and [IsOnsetDateEst] is null or [OnsetDate] is not null and [IsOnsetDateEst] is not null),
    CONSTRAINT [CK_Case_MonthsPostCalving] CHECK (isnull([Sex],'') = 'F' and [MonthsPostCalving] > 0 and [MonthsPostCalving] < 4 and [MonthsPregnant] is null or [MonthsPostCalving] is null),
    CONSTRAINT [CK_Case_MonthsPregnant] CHECK (isnull([Sex],'') = 'F' and [MonthsPregnant] > 0 and [MonthsPregnant] < 10 and [MonthsPostCalving] is null or [MonthsPregnant] is null),
    CONSTRAINT [CK_Case_PurchaseAgeInMonthsNullable] CHECK (isnull([Origin],'') = 'P' and [PurchaseAgeInMonths] is not null or [PurchaseAgeInMonths] is null),
    CONSTRAINT [CK_Case_PurchasedCounty] CHECK (isnull([Origin],'') = 'P' and [PurchasedCounty] is not null or [PurchasedCounty] is null),
    CONSTRAINT [CK_Case_RBSE] CHECK ([RBSE] like '[0-9][0-9][0123456789X][0123456789X][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [CK_Case_SlaughterDate] CHECK ([SlaughterDate] >= isnull([FormADate],'1 January 1970') and [SlaughterDate] >= isnull([BirthDate],'1 January 1970')),
    FOREIGN KEY ([CaseType]) REFERENCES [dbo].[luCaseType] ([Code]),
    CONSTRAINT [FK_Case_Farm] FOREIGN KEY ([CPHH]) REFERENCES [dbo].[Farm] ([CPHH]),
    CONSTRAINT [FK_Case_luAnimalOrigin] FOREIGN KEY ([Origin]) REFERENCES [dbo].[luAnimalOrigin] ([Code]),
    CONSTRAINT [FK_Case_luAnimalStatus] FOREIGN KEY ([DamStatus]) REFERENCES [dbo].[luAnimalStatus] ([Code]),
    CONSTRAINT [FK_Case_luBirthDateSource] FOREIGN KEY ([BirthDateSource]) REFERENCES [dbo].[luBirthDateSource] ([Code]),
    CONSTRAINT [FK_Case_luBreed] FOREIGN KEY ([Breed]) REFERENCES [dbo].[luBreed] ([Code]),
    CONSTRAINT [FK_Case_luBSECounty] FOREIGN KEY ([PurchasedCounty]) REFERENCES [dbo].[luBSECounty] ([Code]),
    CONSTRAINT [FK_Case_luCaseFate] FOREIGN KEY ([Fate]) REFERENCES [dbo].[luCaseFate] ([Code]),
    CONSTRAINT [FK_Case_luReportedLocation] FOREIGN KEY ([ReportedLocation]) REFERENCES [dbo].[luReportedLocation] ([Code]),
    CONSTRAINT [FK_Case_luSex] FOREIGN KEY ([Sex]) REFERENCES [dbo].[luSex] ([Code]),
    CONSTRAINT [FK_Case_luSurvey] FOREIGN KEY ([Survey]) REFERENCES [dbo].[luSurvey] ([Code]),
    CONSTRAINT [FK_Case_luTestResult3] FOREIGN KEY ([FinalResult]) REFERENCES [dbo].[luTestResult] ([Code]),
    CONSTRAINT [FK_Case_luTestType3] FOREIGN KEY ([Methodology]) REFERENCES [dbo].[luTestType] ([Code]),
    CONSTRAINT [FK_Case_luValuationAge] FOREIGN KEY ([ValuationAge]) REFERENCES [dbo].[luValuationAge] ([Code])
);


GO
CREATE NONCLUSTERED INDEX [IX_Case_CPHH]
    ON [dbo].[Case]([CPHH] ASC) WITH (FILLFACTOR = 90);


GO
CREATE NONCLUSTERED INDEX [IX_Case_DBSE]
    ON [dbo].[Case]([DBSE] ASC) WITH (FILLFACTOR = 90);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = NULL, @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Case', @level2type = N'COLUMN', @level2name = N'RBSE';

