CREATE TABLE [dbo].[CaseClinical] (
    [RBSE]                 CHAR (9)     NOT NULL,
    [Apprehension]         BIT          NOT NULL,
    [HypersensitiveTouch]  BIT          NOT NULL,
    [HypersensitiveSound]  BIT          NOT NULL,
    [Maniacal]             BIT          NOT NULL,
    [PanicStricken]        BIT          NOT NULL,
    [TemperamentChange]    BIT          NOT NULL,
    [AbnormalHeadCarriage] BIT          NOT NULL,
    [EarTwitching]         BIT          NOT NULL,
    [EarsOddAngle]         BIT          NOT NULL,
    [AbnormalBehaviour]    BIT          NOT NULL,
    [HeadShyness]          BIT          NOT NULL,
    [LickingFlank]         BIT          NOT NULL,
    [LickingNose]          BIT          NOT NULL,
    [Kicking]              BIT          NOT NULL,
    [ReluctantDoorways]    BIT          NOT NULL,
    [HeadPressing]         BIT          NOT NULL,
    [HeadRubbing]          BIT          NOT NULL,
    [TeethGrinding]        BIT          NOT NULL,
    [Blindness]            BIT          NOT NULL,
    [Circling]             BIT          NOT NULL,
    [HindAtaxia]           BIT          NOT NULL,
    [Falling]              BIT          NOT NULL,
    [Paresis]              BIT          NOT NULL,
    [ForeAtaxia]           BIT          NOT NULL,
    [Recumbent]            BIT          NOT NULL,
    [Tremor]               BIT          NOT NULL,
    [KnucklingFetlock]     BIT          NOT NULL,
    [WeightLoss]           BIT          NOT NULL,
    [ConditionLoss]        BIT          NOT NULL,
    [MilkYield]            BIT          NOT NULL,
    [InitialSigns]         VARCHAR (60) NULL,
    [RowStamp]             ROWVERSION   NOT NULL,
    CONSTRAINT [PK_ClinicalCase] PRIMARY KEY CLUSTERED ([RBSE] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CK_CaseClinical_RBSE] CHECK ([RBSE] like '[0-9][0-9][0123456789X][0123456789X][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [FK_CaseClinical_Case] FOREIGN KEY ([RBSE]) REFERENCES [dbo].[Case] ([RBSE])
);

