CREATE TABLE [dbo].[Farm] (
    [CPHH]                   CHAR (11)     NOT NULL,
    [IsNonGBFarm]            BIT           CONSTRAINT [DF_Farm_IsNonGBFarm] DEFAULT (0) NOT NULL,
    [OwnerName]              VARCHAR (100) NOT NULL,
    [Address1]               VARCHAR (50)  NOT NULL,
    [Address2]               VARCHAR (50)  NULL,
    [Address3]               VARCHAR (50)  NULL,
    [Postcode]               VARCHAR (10)  NULL,
    [Parish]                 VARCHAR (50)  NULL,
    [District]               VARCHAR (50)  NULL,
    [County]                 VARCHAR (15)  NOT NULL,
    [CorrespondenceAddress1] VARCHAR (50)  NULL,
    [CorrespondenceAddress2] VARCHAR (50)  NULL,
    [CorrespondenceAddress3] VARCHAR (50)  NULL,
    [CorrespondencePostcode] VARCHAR (10)  NULL,
    [MapReference]           CHAR (8)      NULL,
    [Herdmark1]              VARCHAR (8)   NULL,
    [Herdmark2]              VARCHAR (8)   NULL,
    [Herdmark3]              VARCHAR (8)   NULL,
    [NumericHerdmark1]       CHAR (6)      NULL,
    [NumericHerdmark2]       CHAR (6)      NULL,
    [AHO]                    CHAR (2)      NULL,
    [HerdType]               CHAR (1)      NULL,
    [PedigreeType]           CHAR (2)      NULL,
    [IsDealer]               BIT           CONSTRAINT [DF_Farm_IsDealer] DEFAULT (0) NOT NULL,
    [ADNSRegionID]           INT           NULL,
    [RowStamp]               ROWVERSION    NOT NULL,
    CONSTRAINT [PK_Farm] PRIMARY KEY CLUSTERED ([CPHH] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [CK_Farm_ADNSRegionID] CHECK ([IsNonGBFarm] = 1 and [ADNSRegionID] is null or [IsNonGBFarm] = 0 and [ADNSRegionID] is not null),
    CONSTRAINT [CK_Farm_AHO] CHECK ([IsNonGBFarm] = 1 and [AHO] is null or [IsNonGBFarm] = 0),
    CONSTRAINT [CK_Farm_CPHH] CHECK ([CPHH] like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [CK_Farm_MapReference] CHECK ([MapReference] like '[A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [CK_Farm_NumericHerdmark1] CHECK ([NumericHerdmark1] like '[0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [CK_Farm_NumericHerdmark2] CHECK ([NumericHerdmark2] like '[0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [CK_Farm_Parish] CHECK ([IsNonGBFarm] = 1 and [Parish] is null or [IsNonGBFarm] = 0 and [Parish] is not null),
    CONSTRAINT [FK_Farm_luAHO] FOREIGN KEY ([AHO]) REFERENCES [dbo].[luAHO] ([Code]),
    CONSTRAINT [FK_Farm_luBSECounty] FOREIGN KEY ([County]) REFERENCES [dbo].[luBSECounty] ([Code]),
    CONSTRAINT [FK_Farm_luHerdType] FOREIGN KEY ([HerdType]) REFERENCES [dbo].[luHerdType] ([Code]),
    CONSTRAINT [FK_Farm_luPedigree] FOREIGN KEY ([PedigreeType]) REFERENCES [dbo].[luPedigreeType] ([Code])
);

