CREATE TABLE [dbo].[tmpCaseADNSBackup] (
    [RBSE]                    CHAR (9)      NOT NULL,
    [CPHH]                    CHAR (11)     NOT NULL,
    [EartagHerdmark]          VARCHAR (8)   NULL,
    [Eartag]                  VARCHAR (25)  NULL,
    [IsNonGBCase]             BIT           NOT NULL,
    [PreviousEartag]          VARCHAR (25)  NULL,
    [BSE1ReceivedDate]        DATETIME      NULL,
    [FormADate]               DATETIME      NULL,
    [FormAResubmittedDate]    DATETIME      NULL,
    [FormBDate]               DATETIME      NULL,
    [Fate]                    VARCHAR (4)   NULL,
    [FormCDate]               DATETIME      NULL,
    [IsPurchaserBSE1Received] BIT           NOT NULL,
    [IsBreederBSE1Received]   BIT           NOT NULL,
    [IsVendor1BSE1Received]   BIT           NOT NULL,
    [IsHomebredBSE1Received]  BIT           NOT NULL,
    [IsSummarySheetReceived]  BIT           NOT NULL,
    [IsPaperworkComplete]     BIT           NOT NULL,
    [Test1Type]               VARCHAR (10)  NULL,
    [Test1Result]             VARCHAR (5)   NULL,
    [Test2Type]               VARCHAR (10)  NULL,
    [Test2Result]             VARCHAR (5)   NULL,
    [Test3Type]               VARCHAR (10)  NULL,
    [Test3Result]             VARCHAR (5)   NULL,
    [FinalResultDate]         DATETIME      NULL,
    [FinalResult]             VARCHAR (5)   NULL,
    [Methodology]             VARCHAR (10)  NULL,
    [DBSE]                    CHAR (7)      NULL,
    [ReportedLocation]        VARCHAR (5)   NULL,
    [Survey]                  VARCHAR (4)   NULL,
    [Notes]                   VARCHAR (500) NULL,
    [BirthDate]               DATETIME      NULL,
    [IsBAB]                   BIT           NULL,
    [IsBirthDateEst]          BIT           NULL,
    [DamStatus]               VARCHAR (9)   NULL,
    [BirthDateSource]         VARCHAR (5)   NULL,
    [ValuationAge]            CHAR (1)      NULL,
    [Sex]                     CHAR (1)      NULL,
    [Breed]                   VARCHAR (20)  NULL,
    [Origin]                  CHAR (1)      NULL,
    [PurchaseDate]            DATETIME      NULL,
    [PurchaseAgeInMonths]     SMALLINT      NULL,
    [PurchasedCounty]         VARCHAR (15)  NULL,
    [HerdEntryDate]           DATETIME      NULL,
    [OnsetDate]               DATETIME      NULL,
    [IsOnsetDateEst]          BIT           NULL,
    [MonthsPregnant]          TINYINT       NULL,
    [MonthsPostCalving]       TINYINT       NULL,
    [OnsetAgeInMonths]        SMALLINT      NULL,
    [SlaughterDate]           DATETIME      NULL,
    [EmailSentToADNSDate]     DATETIME      NULL,
    [ADNSReferenceYear]       SMALLINT      NULL,
    [ADNSReferenceNumber]     INT           NULL,
    [RetrospectiveTestType]   VARCHAR (10)  NULL,
    [RetrospectiveResult]     VARCHAR (5)   NULL,
    [RetrospectiveResultDate] DATETIME      NULL,
    [RetrospectiveComment]    VARCHAR (500) NULL,
    [RowStamp]                ROWVERSION    NOT NULL
);

